# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Compter le nombre d'auteurs
      - name: Count authors in authors.txt
        run: |
          if [ -f authors.txt ]; then
            count=$(wc -l < authors.txt)
            echo "Number of authors: $count"
            echo "authors_count=$count" >> $GITHUB_ENV
          else
            echo "authors.txt file not found!"
            exit 1
          fi

      # Étape 3 : Afficher le nombre d'auteurs
      - name: Display the number of authors
        run: |
          echo "There are ${{ env.authors_count }} authors in authors.txt"
